name: OperatorsList
version: 1.0
main: com.bartuabihd.oplist.OPList
author: BartuAbiHD
description: Show operators.
api-version: "1.13"

commands:
  oplist:
    description: Show operators.
    usage: /oplist
    aliases: [op list]
